# Generated by Django 5.0.1 on 2024-10-26 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_estado_descripcion'),
        ('core', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocualidad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.estado'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.AlterField(
            model_name='puesto',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.estado'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.estado'),
        ),
        migrations.RemoveField(
            model_name='rol',
            name='estado',
        ),
        migrations.AlterField(
            model_name='pais',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.estado'),
        ),
        migrations.AlterField(
            model_name='club',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.estado'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.estado'),
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='rolpermiso',
            name='estado',
        ),
        migrations.AlterField(
            model_name='cualidad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.estado'),
        ),
        migrations.RemoveField(
            model_name='rolpermiso',
            name='permiso',
        ),
        migrations.RemoveField(
            model_name='rolpermiso',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AlterUniqueTogether(
            name='rolpermiso',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jugadores_eliminados', to='adminpanel.usuario'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jugadores_creados', to='adminpanel.usuario'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jugadores_actualizados', to='adminpanel.usuario'),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='RolPermiso',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
