# Generated by Django 5.0.1 on 2024-10-25 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=15, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.estado')),
            ],
            options={
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50, unique=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.estado')),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.estado')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.rol')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.estado')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.rol')),
            ],
            options={
                'verbose_name_plural': 'roles y permisos',
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
