# Generated by Django 5.0.1 on 2024-10-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='descripcion',
            field=models.TextField(max_length=10),
        ),
    ]
