# Generated by Django 5.0.1 on 2024-10-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_permiso_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
